<?xml version="1.0" encoding="utf-8"?><Database Name="FantasyFootball" Class="FantasyFootballDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(local);Initial Catalog=FantasyFootball;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FantasyFootballConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Players" Member="Players">
    <Type Name="Player">
      <Column Name="player_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="last_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="position_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="team_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="college_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Position_Player" Member="Position" ThisKey="position_id" OtherKey="position_id" Type="Position" IsForeignKey="true" />
      <Association Name="Team_Player" Member="Team" ThisKey="team_id" OtherKey="team_id" Type="Team" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Positions" Member="Positions">
    <Type Name="Position">
      <Column Name="position_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="position_name" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Position_Player" Member="Players" ThisKey="position_id" OtherKey="position_id" Type="Player" />
    </Type>
  </Table>
  <Table Name="dbo.Teams" Member="Teams">
    <Type Name="Team">
      <Column Name="team_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="team_abbr" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="team_name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="team_city" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="div_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Team_Player" Member="Players" ThisKey="team_id" OtherKey="team_id" Type="Player" />
    </Type>
  </Table>
</Database>